[project]
name = "vibetuner-scaffolding"
version = "2.17.3"
requires-python = ">=3.11"
dependencies = []

vibetuner = { path = "./packages/vibetuner-py" }

[dependency-groups]
dev = ["vibetuner[dev]"]
