[project]
name = "vibetuner-scaffolding"
version = "0.0.1"
requires-python = ">=3.11"

[dependency-groups]
dev = [
  "vibetuner[dev]>=2.9.1",
  # Add below this line any dev dependencies you need for development
]
docs = [
  "mkdocs>=1.6.1",
  "mkdocs-material>=9.6.23",
]
