[project]
name = "vibetuner-scaffolding"
version = "0.0.1"
requires-python = ">=3.10"

[dependency-groups]
dev = [
  "vibetuner[dev]>=2.6.1",
  # Add below this line any dev dependencies you need for development
]
