[project]
name = "scaffolding"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "fastapi>=0.115.12",
    "fasthx[jinja]>=2.3.3",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
]
