[project]
name = "scaffolding"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cloudflare>=4.2.0",
    "rich>=14.0.0",
]

[dependency-groups]
dev = [
    "asyncer>=0.0.8",
    "fastapi[standard]>=0.115.12",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
    "rich>=14.0.0",
    "ruff>=0.11.11",
    "typer-slim[standard]>=0.15.4",
]

[tool.ruff.lint]
extend-select = [
    # E and F are enabled by default
    'B',      # flake8-bugbear
    'C4',     # flake8-comprehensions
    'C90',    # mccabe
    'I',      # isort
    'N',      # pep8-naming
    'Q',      # flake8-quotes
    'RUF100', # ruff (unused noqa)
    'S',      # flake8-bandit
    'W',      # pycodestyle
]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
