[project]
name = "scaffolding"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "arel>=0.3.0",
    "asyncer>=0.0.8",
    "beanie[zstd]>=1.29.0",
    "click>=8.1.8",
    "cloudflare>=4.2.0",
    "fastapi[standard]>=0.115.12",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "pydantic-extra-types[pycountry]>=2.10.4",
    "pydantic-settings>=2.9.1",
    "pyyaml>=6.0.2",
    "redis[hiredis]>=5.3.0",
    "rich>=14.0.0",
    "ruff>=0.11.11",
    "starlette-babel>=1.0.3",
    "starlette-cramjam>=0.5.0",
    "streaq>=0.2.1",
    "typer-slim[standard]>=0.15.4",
]

[tool.ruff.lint]
extend-select = [
    # E and F are enabled by default
    'B',      # flake8-bugbear
    'C4',     # flake8-comprehensions
    'C90',    # mccabe
    'I',      # isort
    'N',      # pep8-naming
    'Q',      # flake8-quotes
    'RUF100', # ruff (unused noqa)
    'S',      # flake8-bandit
    'W',      # pycodestyle
]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
