[global]
# List of file/directory patterns to exclude from linting
exclude = [
  # Common directories to exclude
  ".git",
  ".github",
  "node_modules",
  ".venv",

  # We only have CLAUDE.md symlinks, hence we don't need to check
  "CLAUDE.md",
  "CHANGELOG.md",
]

# Rule-specific configurations
[MD013]
# Line length
line_length = 120

# Per file ignores
[per-file-ignores]
"**/.claude/agents/*.md" = [
  "MD013", # Line length
  "MD033", # Inline HTML
]
"**/.claude/commands/*.md" = [
  "MD013", # Line length
  "MD033", # Inline HTML
]
